[features]
seeds = false
skip-lint = false
[programs.localnet]
rb_contracts = "4znujrwLsjKTNQxLRncUYdGLAHnqsVLQarNP9jVEA57n"
renaiss_block = "9ZACvfz6GNqa7fvtXTbsWUKjgzHUeJwxg4qiG8oRB7eH"
[programs.devnet]
renaiss_block = "9ZACvfz6GNqa7fvtXTbsWUKjgzHUeJwxg4qiG8oRB7eH"
rb_contracts = "4znujrwLsjKTNQxLRncUYdGLAHnqsVLQarNP9jVEA57n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/davidsong/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"
